# Rustyll Demo Site Configuration
title: Rustyll Demo Site
description: A demonstration of Rustyll's Jekyll-compatible static site generator
author:
  name: Rustyll Team
  email: hello@rustyll.dev

# Site settings
baseurl: ""
url: "http://localhost:4000"
timezone: UTC

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name/
  docs:
    output: true
    permalink: /docs/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Rustyll Team"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "doc"

# Plugins (Rustyll built-in)
plugins:
  - feed
  - seo
  - sitemap

# Exclude from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor